apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-appsource-controller
  labels:
    app.kubernetes.io/name: argocd-appsource-controller
    app.kubernetes.io/part-of: argocd-appsource
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-appsource-controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-appsource-controller
    spec:
      # volumes:
      #   - name: argocd-appsource-config-volume
      #     configMap:
      #       name: argocd-appsource-cm
      containers:
        - command:
            - /manager
          image: quay.io/argoprojlabs/argocd-appsource:latest
          imagePullPolicy: Always
          name: manager
          env:
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-appsource-secret
                  key: argocd-token

      serviceAccountName: argocd-appsource-controller
